// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckTitleDuplicate(arg1, arg2) {
  return window['go']['main']['App']['CheckTitleDuplicate'](arg1, arg2);
}

export function CompressImage(arg1, arg2) {
  return window['go']['main']['App']['CompressImage'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SaveAndCompressImage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveAndCompressImage'](arg1, arg2, arg3);
}

export function SavePost(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['SavePost'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectImageDirectory() {
  return window['go']['main']['App']['SelectImageDirectory']();
}
