// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CommitToGit(arg1:string,arg2:string):Promise<void>;

export function CompressImage(arg1:string,arg2:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function IsValidGitRepo(arg1:string):Promise<boolean>;

export function SaveAndCompressImage(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SavePost(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SelectGitRepoDirectory():Promise<string>;

export function SelectImageDirectory():Promise<string>;
