// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CommitToGit(arg1, arg2) {
  return window['go']['main']['App']['CommitToGit'](arg1, arg2);
}

export function CompressImage(arg1, arg2) {
  return window['go']['main']['App']['CompressImage'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InitGitRepo(arg1) {
  return window['go']['main']['App']['InitGitRepo'](arg1);
}

export function IsValidGitRepo(arg1) {
  return window['go']['main']['App']['IsValidGitRepo'](arg1);
}

export function SavePost(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SavePost'](arg1, arg2, arg3, arg4);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectGitRepoDirectory() {
  return window['go']['main']['App']['SelectGitRepoDirectory']();
}

export function SelectImageDirectory() {
  return window['go']['main']['App']['SelectImageDirectory']();
}
